### ISSUE TITLE
Japanese translation and removing Interstellar Mode

### ISSUE THREAD

**Issue by TRSasasusu** [2walker2/NHJamTeamErnesto#1]
Hello, I make a Japanese translation: [japanese.txt](https://github.com/2walker2/NHJamTeamErnesto/files/11926715/japanese.txt)
Please rename it into `japanese.json` (GitHub's Issue cannot take `.json` file directly...) and move it into `translations/.` directory.

Also, I noticed we can still go to Hearthian's system with the Interstellar Mode.
It is inconsistent with the story of your mod.
So, adding [SolarSystem.txt](https://github.com/2walker2/NHJamTeamErnesto/files/11926749/SolarSystem.txt) (please change its extension into `.json`) into `systems/.` and add a line `"canEnterViaWarpDrive": false,` into `systems/2walker2.OogaBooga.json` can remove the Interstellar Mode.

**Comment by TextureTurtle** [comment]
Merged
